/* eslint-disable max-len */
/* eslint-disable camelcase */

import { clone } from 'ramda';

const regexp =
  "^([А-Я,а-я,Ё,ё,A-Z,a-z\\&#34;\\'\\№,\\:\\s\\.\\,\\\\\\\\,\\/\\,\\-\\+\\d\\?\\?\\?\\,\\?,\\>\\,\\&lt;\\,\\=\\,\\*\\(\\)\\%\\@\\?\\?\\?\\?\\_\\-\\:\\?\\?\\?\\?\\?\\?\\?\\`\\# ]){5,210}$";

const ORDER = {
  step: '1',
  services: {
    serv: {
      pars: {
        par: [
          {
            step: '1',
            name: 'PAYEEACC',
            fullname: 'Cчет получателя платежа',
            comment: '',
            type: 'I',
            min_length: '20',
            max_length: '20',
            isValidateOnLine: '1',
            isRequired: '1',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value: '',
            reg_exp: '',
            from_debt: '0',
          },
          {
            step: '1',
            name: 'PAYEEINN',
            fullname: 'ИНН',
            comment: '',
            type: 'I',
            min_length: '10',
            max_length: '10',
            isValidateOnLine: '1',
            isRequired: '1',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value: '',
            reg_exp: '',
            from_debt: '0',
          },
          {
            step: '1',
            name: 'PAYEEBIC',
            fullname: 'БИК',
            comment: '',
            type: 'I',
            min_length: '9',
            max_length: '9',
            isValidateOnLine: '1',
            isRequired: '1',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value: '',
            reg_exp: '',
            from_debt: '0',
          },
          {
            step: '1',
            name: 'PAYEECORR',
            fullname: 'К/С',
            comment: '',
            type: 'I',
            min_length: '1',
            max_length: '20',
            isValidateOnLine: '1',
            isRequired: '1',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value: '',
            reg_exp: '',
            from_debt: '0',
          },
          {
            step: '1',
            name: 'PAYEEBANK',
            fullname: 'Банк получателя',
            comment: '',
            type: 'C',
            min_length: '1',
            max_length: '99',
            isValidateOnLine: '1',
            isRequired: '1',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value: 'ГУ БАНКА РОССИИ ПО ЦФО',
            reg_exp: '',
            from_debt: '0',
          },
          {
            step: '1',
            name: 'PAYEENAME',
            fullname: 'Название организации',
            comment: 'Полное название организации, как в платежной квитанции',
            type: 'C',
            min_length: '1',
            max_length: '160',
            isValidateOnLine: '1',
            isRequired: '1',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value:
              'УФК по г Москве ТУ Росимущества в городе Москве лс 04731А18710',
            reg_exp:
              '^([a-zA-Z0-9 %"№,()""-/!?]*[а-яА-ЯЁё][a-zA-Z0-9 %"№,()""-/!?]*){3,}$',
            from_debt: '0',
          },
          {
            step: '1',
            name: 'PAYEEKPP',
            fullname: 'КПП',
            comment: '9 цифр',
            type: 'I',
            min_length: '9',
            max_length: '9',
            isValidateOnLine: '1',
            isRequired: '1',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value: '',
            reg_exp: '^([0]{1})$|^([0-9]{9})$',
            from_debt: '0',
          },
          {
            step: '1',
            name: 'CBC',
            fullname: 'КБК',
            comment: '20 цифр или 0',
            type: 'C',
            min_length: '0',
            max_length: '20',
            isValidateOnLine: '0',
            isRequired: '1',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value: '16711105021016000120',
            reg_exp:
              '^(?!(00000000000000000000))$|^([0]{1})$|^[0-9]{17}(110|150|151|152|153|160|170|410|420|430|440|042|022)|^[0-9]{17}(02|12|13|14|18)[0-9]{1}$',
            from_debt: '0',
          },
          {
            step: '1',
            name: 'OKTMO',
            fullname: 'ОКТМО',
            comment: '8 цифр или 0',
            type: 'C',
            min_length: '0',
            max_length: '8',
            isValidateOnLine: '0',
            isRequired: '1',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value: '45378000',
            reg_exp: '^([0]{1})$|^([0-9]{8})$',
            from_debt: '0',
          },
          {
            step: '1',
            name: 'UIN',
            fullname: 'УИН (при наличии)',
            comment:
              'Уникальный идентификатор начисления указан в платёжной квитанции и состоит из 20-25 символов.  Если его нет, оставьте поле пустым',
            type: 'T',
            min_length: '0',
            max_length: '25',
            isValidateOnLine: '0',
            isRequired: '0',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value: '',
            reg_exp: '',
            from_debt: '0',
          },
          {
            step: '1',
            name: 'ВИД_ДОК',
            fullname: 'Вид документа',
            comment: 'Документ, удостоверяющий личность',
            type: 'M',
            min_length: '0',
            max_length: '250',
            isValidateOnLine: '1',
            isRequired: '1',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value: '',
            reg_exp: '',
            from_debt: '0',

            par_list: [
              { value: 'ПАСПОРТ РФ' },
              { value: 'СВИД О РОЖДЕНИИ' },
              { value: 'ИНН' },
              { value: 'ВОДИТ УДОСТОВЕРЕНИЕ' },
              { value: 'СВИД_РЕГ_ТС' },
              { value: 'ПАСПОРТ МОРЯКА' },
              { value: 'УДОСТОВЕР ВОЕНСЛУЖ' },
              { value: 'ВОЕННЫЙ БИЛЕТ' },
              { value: 'СПРАВКА ОБ ОСВОБ' },
              { value: 'ВРЕМЕН УДОСТОВЕР' },
              { value: 'ПАСПОРТ ИН ГРАЖД' },
              { value: 'ВИД НА ЖИТЕЛЬСТВО' },
              { value: 'РАЗРЕШ ВРЕМ ПРОЖИВ' },
              { value: 'УДОСТОВЕР БЕЖЕНЦА' },
              { value: 'МИГРАЦИОННАЯ КАРТА' },
              { value: 'ПАСПОРТ СССР' },
              { value: 'СНИЛС' },
              { value: 'ОХОТНИЧИЙ БИЛЕТ' },
              { value: 'РАЗРЕШ НА ОРУЖИЕ' },
              { value: 'ЗАГРАНПАСПОРТ' },
              { value: 'СВИД НА ВРЕМЕННОЕ УБЕЖИЩЕ НА ТЕР.РФ' },
              { value: 'СВИД О РАССМ. ХОДАТ-ВА ПО СУЩЕСТВУ' },
            ],
          },

          {
            step: '2',
            name: 'НОМЕР ДОКУМЕНТА',
            fullname: 'Серия и номер документа',
            comment:
              'Введите серию и номер документа, лица за кого оплачивается услуга',
            type: 'C',
            min_length: '9',
            max_length: '12',
            isValidateOnLine: '0',
            isRequired: '1',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value: '',
            reg_exp: '',
            from_debt: '0',
          },
          {
            step: '2',
            name: 'FIO',
            fullname: 'ФИО Плательщика',
            comment: 'Фамилия Имя Отчество полностью',
            type: 'C',
            min_length: '0',
            max_length: '70',
            isValidateOnLine: '1',
            isRequired: '1',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value: '',
            reg_exp: '^[а-яА-ЯЁё -]{1,60}$',
            from_debt: '0',
          },
          {
            step: '3',
            name: 'PURPOSE',
            fullname: 'Назначение платежа',
            comment: 'Это поможет организации понять, за что вы платите.',
            type: 'C',
            min_length: '0',
            max_length: '125',
            isValidateOnLine: '0',
            isRequired: '0',
            isVisible: '1',
            isScanable: '0',
            isEditable: '1',
            isPrinted: '1',
            double_input: '0',
            value: '',
            reg_exp: regexp,
            from_debt: '0',
          },
          {
            step: '3',
            name: 'УИП',
            fullname: 'Уникальный идентификатор платежа',
            comment: '',
            type: 'N',
            min_length: '32',
            max_length: '32',
            isValidateOnLine: '0',
            isRequired: '0',
            isVisible: '1',
            isScanable: '0',
            isEditable: '0',
            isPrinted: '1',
            double_input: '0',
            value: '',
            reg_exp: '',
            from_debt: '0',
          },
          {
            step: '3',
            name: 'ИПГУ',
            fullname: 'ИПГУ',
            comment: '',
            type: 'C',
            min_length: '12',
            max_length: '25',
            isValidateOnLine: '0',
            isRequired: '0',
            isVisible: '1',
            isScanable: '0',
            isEditable: '0',
            isPrinted: '1',
            double_input: '0',
            value: '',
            reg_exp: '',
            from_debt: '0',
          },
          {
            step: '3',
            name: 'EXCLUDE_REQS',
            fullname: 'Скрытие реквизитов',
            comment: '',
            type: 'C',
            min_length: '1',
            max_length: '250',
            isValidateOnLine: '0',
            isRequired: '0',
            isVisible: '1',
            isScanable: '0',
            isEditable: '0',
            isPrinted: '1',
            double_input: '0',
            value: '',
            reg_exp: '',
            from_debt: '0',
          },
        ],
      },
    },
  },
};

const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

export const upsMock = async (incomingOrder) => {
  const order = clone(incomingOrder);

  if (order.step === '0') {
    order.step = '1';
    order.services = clone(ORDER.services);
  } else if (order.step === '1') {
    order.step = '2';
  } else if (order.step === '2') {
    order.step = '3';
  } else if (order.step === '3') {
    order.step = 'summa';
  } else if (order.step === 'summa') {
    order.step = 'pay';
    order.commission = '100.10';
  }

  await delay(50);

  return Promise.resolve({ data: order });
};
